# Generated by Django 4.0.4 on 2023-01-19 20:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Jump',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jumpnum', models.CharField(max_length=30)),
                ('date', models.DateField(verbose_name='mm/dd/yyyy')),
                ('place', models.CharField(max_length=30)),
                ('aircraft', models.CharField(max_length=30)),
                ('equipment', models.CharField(max_length=30)),
                ('altitude', models.IntegerField(max_length=6)),
                ('freefall', models.IntegerField(max_length=3)),
                ('description', models.CharField(max_length=500)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
