# Generated by Django 4.1.5 on 2023-02-22 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jump', '0002_jump_weather_alter_jump_altitude_alter_jump_freefall'),
    ]

    operations = [
        migrations.AddField(
            model_name='jump',
            name='picture',
            field=models.ImageField(default='backend\\jump\\kamil-pietrzak-AlA8S9tALAs-unsplash.jpg', upload_to='<int:pk>/'),
        ),
    ]
